### ISSUE TITLE
Planning ROS Hardware Interface

### ISSUE THREAD

**Issue by acbuynak** [OSU-AIMS/coaliron_16ton_support#2]
The structure to implement ROS client-based control onto the the P1AM-100 controller setup, but not fully implemented.

### Design Decisions remaining:
* should we allow both Serial and ROS -based remote connections to be open at the same time
* hydraulic motor power status. There's an open channel in the power button, I'd like to have a connection to the PLC which checks for whether it's open or closed to have remote motion requests rejected if power is off

### Controller Hardware Interface Design
I am considering the code on the PLC to be the _controller hardware interface_ and build in the option for a true controller on ROS (not implemented on the PLC). This is standard practice for the [ros_control](http://wiki.ros.org/ros_control) package and most all ROS robots.

The `h_controller.ino` interface method is heavily dependent on how the hydraulic value operates. Switching out the valve will change most of the code in this file and need to be rewritten.

Current situation is weird from a controller standpoint because it is a 3-state control: `up, off, down`. It's effectively a position-based controller, but not a very good one because how poorly we can control the position of the actuator.
It might be useful if the new valve can be treated as an effort based controller, or minimally a more accurate position-based controller. This may simplify the hardware interface.

End of day: I think getting rid of overshoot is going to be important from a control perspective. Even for the forging setup.

### Force Application Method
I think the 'set target position inside of material' method of applying force is still the right path to follow. I don't know of any other way yet.

### Industrial Robot Driver Specification
http://wiki.ros.org/Industrial/Industrial_Robot_Driver_Spec

**Comment by acbuynak** [comment]
Development for this Issue is underway in branch `ros_client_interface`

**Comment by acbuynak** [comment]
Notes on types of controllers:
> Controllers are defined by the type of control input and the type of output they use to drive the joint.

> The position-based JointTrajectoryController of `ros_control` is an open-loop controller. Position commands are forwarded to the hardware interface and the deviation is measured inside the controller’s feedback. If the path deviation gets too large, the action sent to the controller will simply fail, there won’t be any corrections.

> Effort controllers control the force of a linear actuator. They are named effort as the interface agnostic to the joint type.

**Comment by TobiasJMahan** [comment]
> * hydraulic motor power status. There's an open channel in the power button, I'd like to have a connection to the PLC which checks for whether it's open or closed to have remote motion requests rejected if power is off

In the PLC we can devote digital input pins 4 & 5 to checking if the power is on or off

**Comment by hansen95** [comment]
> should we allow both Serial and ROS -based remote connections to be open at the same time
If it is not creating a problem, I suggest keeping both for now. 

> hydraulic motor power status. There's an open channel in the power button, I'd like to have a connection to the PLC which checks for whether it's open or closed to have remote motion requests rejected if power is off
Sounds like a good idea, as long as we're sure about the wiring. I'm happy to assist.

> Switching out the valve will change most of the code in this file and need to be rewritten.
We are not planning to switch out the valve. We are adding a flow control valve that will allow us to slow the press, but the existing solenoid valve will continue to control up/down/off behavior.

**Comment by acbuynak** [comment]
> We are adding a flow control valve that will allow us to slow the press, but the existing solenoid valve will continue to control up/down/off behavior.

Will the flow control valve be mechanically or electronically controlled? Ie, can we control the speed from the PLC?


**Idea for the Remote Connections**
How about using the onboard toggle switch to change between remote modes? Selecting either `ROS` or `Serial`

**Comment by hansen95** [comment]
> Will the flow control valve be mechanically or electronically controlled? Ie, can we control the speed from the PLC?

The flow control valve takes a 12V PWM signal (max 1A). I believe there is an available PWM output on the PLC, but we may need to add a solid state relay to handle the current.

> **Idea for the Remote Connections** How about using the onboard toggle switch to change between remote modes? Selecting either `ROS` or `Serial`

Not sure what toggle switch you're referring to. Also, I don't know what problem with the existing setup the toggle switch is meant to correct. If it fixes something and it's easy to implement, it sounds like a great idea.

**Comment by acbuynak** [comment]
Toggle switch is on the body of PLC. 
Per Manufacturer: The toggle switch be can used like a normal digital input. It doesn't alter any behavior on it's own so make sure to write code to include any desired functionality. 

```C++
pinMode(SWITCH_BUILTIN, INPUT);	 //Set switch to digital input
digitalRead(SWITCH_BUILTIN);     //Read switch state. 1-up, 0-down.
```

**Why do this?**
Mostly code design simplicity. Since both interfaces are actively waiting to receive a motion request, I need a way to set which has priority. Assuming all three connections are 'enabled' at once, I recognize these options..
* Opt 1. Strict ladder priority. 1-Manual,  2-Serial,  3-ROS
* Opt 2. Tree priority. 1-Manual,  2-Serial or ROS based on a state variable 

I think Opt 1 would programmatically annoying to implement and I can't think of a use case.
We should go for Opt2. Only annoying part would be the need to open the cabinet to flip switch if you want to change control states. Further, if we put a digital readout screen on the cabinet, we can show a symbol indicating the current state.

For clarity, the ROS `joint_state` publisher will always report the position regardless of the control mode. This behavior mimics that of the ROS industrial packages. 

I'm planning to hold off on any further development until new flow control valve is installed, but we can continue discussion here.

**Comment by acbuynak** [comment]
PR #3 deploys the `SWITCH_BUILTIN` as a ethernet network connection ON/OFF mode switch.
This effectively enables/disables ROS, though a ROS node handle is still initialize on the system regardless of switch state.

**Comment by acbuynak** [comment]
#11 formalizes ROS interface. Closing this Issue with the release of v0.2.0
